name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install cmake ninja llvm

      - name: Configure CMake
        run: |
          cmake -B build/release \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
            -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
            -G Ninja

      - name: Build
        run: cmake --build build/release --target MotionDesk

      - name: Verify app bundle
        run: |
          ls -la build/release/MotionDesk.app
          file build/release/MotionDesk.app/Contents/MacOS/MotionDesk

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MotionDesk-${{ github.sha }}
          path: build/release/MotionDesk.app
          retention-days: 7
